# Generated by Django 3.0.3 on 2020-03-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
