# Generated by Django 3.0.3 on 2020-03-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_players_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
