# Generated by Django 3.0.3 on 2020-03-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20200305_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
