# Generated by Django 3.0.3 on 2020-03-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_is_winner'),
        ('game', '0004_auto_20200303_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='qualified_team',
            new_name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(default=194, on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='team.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(default=195, on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='team.Team'),
        ),
    ]
